oc_platform_homepage:
    path:     /
    defaults: { _controller: AppBundle:Car:index }
    
hello_the_world:
    path : /hello-world
    defaults: {_controller: AppBundle:Car:index}
    
    
oc_platform_home:
    path:      /{page}
    defaults:
        _controller: AppBundle:Car:index
        page:        1
    requirements:
        page: \d*
    
oc_platform_view:
    path:      /car/{id}
    defaults:
        _controller: AppBundle:Car:view
    requirements:
        id: \d+
        
oc_platform_view_post:
    path:      /post/{id}
    defaults:
        _controller: AppBundle:Post:view
    requirements:
        id: \d+

oc_platform_add:
    path:      /add
    defaults:
        _controller: AppBundle:Car:add

oc_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: AppBundle:Car:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: AppBundle:Car:delete
    requirements:
        id: \d+


oc_platform_test:
    path:      /test
    defaults:
        _controller: AppBundle:Car:test
        
oc_platform_ajax:
    path: /listviaajax
    defaults:
        _controller: AppBundle:Car:indexAjax
    